In [ ]:
1

In [ ]:
1+2


In [ ]:
4%5

In [ ]:
6//7

In [ ]:
10 ** 2


In [ ]:
10 ** 10


In [ ]:
10 * str

In [ ]:
10 * 'str'

# String

In [ ]:
name = "Disha"

In [ ]:
first_name = "Disha"
last_name = "Verma"

In [ ]:
print("My first name is {} and last name is {}".format(first_name, last_name))

In [ ]:
print("My first name is {} and last name is {}".format(last_name , first_name))

In [ ]:
print("My name is {first} and last name is {last}".format(last = last_name, first = first_name))

In [ ]:
type([])

In [ ]:
llist = [1, 2, 3, 4]
llist.extend([6, 7])
print(llist)

In [ ]:
llist = [1, 2, 3, 4]
llist.append([8,9])
print(llist)

In [ ]:
sets = {'Avengers', 'Hulk', 'Batman'}

In [ ]:
sets.add("Spider man")

In [ ]:
print(sets)

In [ ]:
dic = {}
type(dic)

In [ ]:
sets = {}
type(sets)


In [ ]:
my_Set = set()

In [ ]:
type (my__Set)

In [ ]:
type(my_set)

In [ ]:
type(my_Set)

In [ ]:
car1_model = {'Mercedes':1970}
car2_model = {'Alto':1980}
car3_model = {'XUV': 1580}

In [ ]:
cars = {'car1': car1_model, 'car2' : car2_model, 'car3' : car3_model}
print(cars)

In [ ]:
print(cars['car1']['Mercedes'])

In [ ]:
my_tup = ()
type(my_tup)

In [ ]:
my_tup = ("Krish", "Ankur", "John")
my_tup[0]

In [ ]:
print(my_tup["Krish"])

In [ ]:
my_tup[0] = "Naik"

In [ ]:
conda install numpy


In [ ]:
import numpy as np

In [3]:
import numpy as np


In [ ]:
my_lst = [1, 2, 3, 4, 5]

In [ ]:
arr = np.array(my_lst)

In [ ]:
print(arr)


In [ ]:
arr.shape

In [ ]:
arr.reshape()

In [3]:
mylst1 = [1,2,3,4,5]
mylst2 = [3,4,5,6,7]
mylst3 = [8,9,7,6,5]
arr = np.array([mylst1, mylst2, mylst3])

In [4]:
arr


array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [8, 9, 7, 6, 5]])

In [5]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [8, 9, 7, 6, 5]])

In [6]:
arr[0:2, 0:2]

array([[1, 2],
       [3, 4]])

In [7]:
arr[1:, 2:4]

array([[5, 6],
       [7, 6]])

In [9]:
arr[1:2, 1:4]

array([[4, 5, 6]])

In [ ]:
arr.shape

In [ ]:
arr.reshape(5, 3)

In [ ]:
arr.reshape(15, 1)

In [ ]:
arr.reshape(1,15)

In [10]:
arr = np.arange(0, 10)

In [11]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
arr = np.arange(0, 10, 2)

In [13]:
arr

array([0, 2, 4, 6, 8])

In [14]:
np.linspace(1, 10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
arr


array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
arr[3:] = 100

In [7]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100])

In [8]:
arr1 = arr

In [9]:
arr1[3:]=500
print(arr1)

[  1   2   3 500 500 500 500 500]


In [10]:
arr


array([  1,   2,   3, 500, 500, 500, 500, 500])

In [11]:
print(arr)

[  1   2   3 500 500 500 500 500]


In [12]:
arr1 = arr.copy()
arr1[3:] = 1000

In [13]:
print(arr1)

[   1    2    3 1000 1000 1000 1000 1000]


In [14]:
print(arr)

[  1   2   3 500 500 500 500 500]


In [15]:
val = 2

In [17]:
arr < val

array([ True, False, False, False, False, False, False, False])

In [18]:
arr * 2

array([   2,    4,    6, 1000, 1000, 1000, 1000, 1000])

In [19]:
arr % 2

array([1, 0, 1, 0, 0, 0, 0, 0])

In [20]:
arr / 2

array([  0.5,   1. ,   1.5, 250. , 250. , 250. , 250. , 250. ])

In [21]:
arr[arr<2]

array([1])

In [22]:
np.arange(0, 10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
np.arange(0, 10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
arr1 = np.arange(0, 10).reshape(5,2)

In [31]:
arr2 = np.arange(0, 10).reshape(2,5)

In [26]:
arr1 * arr2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [32]:
arr1 @ arr2

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [33]:
np.ones(4)

array([1., 1., 1., 1.])

In [34]:
np.ones(4, dtype = int)

array([1, 1, 1, 1])

In [35]:
np.ones((2, 5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
np.random.rand(3,3)

array([[0.45847006, 0.47947297, 0.2553572 ],
       [0.46783866, 0.20932822, 0.59536469],
       [0.47486011, 0.77416077, 0.72422019]])

In [1]:
np.random.randn(4,5)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
np.random.randn(4,5)

array([[ 0.602113  ,  0.35774324,  0.87471688, -0.66828777,  0.31885157],
       [ 0.08744157, -0.55143261, -1.05127878,  2.93740473,  1.04307025],
       [ 1.42454761,  1.05485453,  1.10128369, -0.47862166,  0.6025033 ],
       [ 0.56690989,  1.09627552, -0.35637791, -0.39324757,  1.34264166]])

In [4]:
np.random.randint(4, 99, 6).reshape(2,3)

array([[77, 84, 82],
       [95, 14, 86]], dtype=int32)

In [5]:
np.random.randint(4, 99, 6).reshape(7.6)

TypeError: expected a sequence of integers or a single integer, got '7.6'

In [6]:
np.random.randint(4, 99, 6).reshape(7, 6)

ValueError: cannot reshape array of size 6 into shape (7,6)